// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
 * Maps macOS-specific key code values representing [PhysicalKeyboardKey].
 *
 * MacOS doesn't provide a scan code, but a virtual keycode to represent a physical key.
 */
extern const NSDictionary* keyCodeToPhysicalKey;

/**
 * A map of macOS key codes which have printable representations, but appear
 * on the number pad. Used to provide different key objects for keys like
 * KEY_EQUALS and NUMPAD_EQUALS.
 */
extern const NSDictionary* keyCodeToNumpad;

/**
 * A map of macOS key codes which are numbered function keys, so that they
 * can be excluded when asking "is the Fn modifier down?".
 */
extern const NSDictionary* keyCodeToFunctionKey;

// Several mask constants. See KeyCodeMap.mm for their descriptions.

extern const uint64_t kValueMask;
extern const uint64_t kPlatformMask;
extern const uint64_t kUnicodePlane;
extern const uint64_t kHidPlane;
extern const uint64_t kAutogeneratedMask;
extern const uint64_t kSynonymMask;

/**
 * The code prefix for keys from macOS which do not have a Unicode
 * representation.
 */
static const uint64_t kMacosPlane = 0x00500000000;
