// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "impeller/compiler/spirv_sksl.h"

using namespace spv;
using namespace SPIRV_CROSS_NAMESPACE;
using namespace std;

namespace impeller {
namespace compiler {

string CompilerSkSL::compile() {
  // Do not deal with ES-isms like precision, older extensions and such.
  options.es = false;
  options.version = 450;
  backend.float_literal_suffix = true;
  backend.double_literal_suffix = false;
  backend.long_long_literal_suffix = true;
  backend.uint32_t_literal_suffix = true;
  backend.basic_int_type = "int32_t";
  backend.basic_uint_type = "uint32_t";
  backend.swizzle_is_function = true;
  backend.shared_is_implied = true;
  backend.unsized_array_supported = false;
  backend.explicit_struct_type = true;
  backend.use_initializer_list = true;

  return spirv_cross::CompilerGLSL::compile();
}

void CompilerSkSL::emit_header() {
  statement("// This SkSL shader is autogenerated by spirv-cross.");
  // TODO(zra): Add #defines for SkSL things that have different names
}

}  // namespace compiler
}  // namespace impeller