// Copyright 2018 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// WARNING: This file is machine generated by fidlmerge.

#pragma once

#include <fuchsia/ui/gfx/cpp/fidl.h>

#include "lib/fostr/fidl/fuchsia.ui.gfx/amendments.h"

namespace fuchsia {
namespace ui {
namespace gfx {

std::ostream& operator<<(std::ostream& os, const MeshIndexFormat& value);
std::ostream& operator<<(std::ostream& os, const ShadowTechnique& value);
std::ostream& operator<<(std::ostream& os, const RenderFrequency& value);
std::ostream& operator<<(std::ostream& os, const ImportSpec& value);
std::ostream& operator<<(std::ostream& os, const ValueType& value);
std::ostream& operator<<(std::ostream& os, const HitTestBehavior& value);
std::ostream& operator<<(std::ostream& os, const CreateResourceCmd& value);
std::ostream& operator<<(std::ostream& os, const ReleaseResourceCmd& value);
std::ostream& operator<<(std::ostream& os, const ExportResourceCmdDeprecated& value);
std::ostream& operator<<(std::ostream& os, const ImportResourceCmdDeprecated& value);
std::ostream& operator<<(std::ostream& os, const SetTagCmd& value);
std::ostream& operator<<(std::ostream& os, const DetachCmd& value);
std::ostream& operator<<(std::ostream& os, const SetTranslationCmd& value);
std::ostream& operator<<(std::ostream& os, const SetScaleCmd& value);
std::ostream& operator<<(std::ostream& os, const SetRotationCmd& value);
std::ostream& operator<<(std::ostream& os, const SetAnchorCmd& value);
std::ostream& operator<<(std::ostream& os, const SetSizeCmd& value);
std::ostream& operator<<(std::ostream& os, const SetOpacityCmd& value);
std::ostream& operator<<(std::ostream& os, const SendSizeChangeHintCmdHACK& value);
std::ostream& operator<<(std::ostream& os, const AddChildCmd& value);
std::ostream& operator<<(std::ostream& os, const AddPartCmd& value);
std::ostream& operator<<(std::ostream& os, const DetachChildrenCmd& value);
std::ostream& operator<<(std::ostream& os, const SetShapeCmd& value);
std::ostream& operator<<(std::ostream& os, const SetMaterialCmd& value);
std::ostream& operator<<(std::ostream& os, const SetClipCmd& value);
std::ostream& operator<<(std::ostream& os, const SetHitTestBehaviorCmd& value);
std::ostream& operator<<(std::ostream& os, const SetSemanticVisibilityCmd& value);
std::ostream& operator<<(std::ostream& os, const SetViewPropertiesCmd& value);
std::ostream& operator<<(std::ostream& os, const TakeSnapshotCmdDEPRECATED& value);
std::ostream& operator<<(std::ostream& os, const SetCameraCmd& value);
std::ostream& operator<<(std::ostream& os, const SetCameraTransformCmd& value);
std::ostream& operator<<(std::ostream& os, const SetCameraProjectionCmd& value);
std::ostream& operator<<(std::ostream& os, const SetStereoCameraProjectionCmd& value);
std::ostream& operator<<(std::ostream& os, const SetCameraClipSpaceTransformCmd& value);
std::ostream& operator<<(std::ostream& os, const SetCameraPoseBufferCmd& value);
std::ostream& operator<<(std::ostream& os, const SetLightColorCmd& value);
std::ostream& operator<<(std::ostream& os, const SetLightDirectionCmd& value);
std::ostream& operator<<(std::ostream& os, const AddLightCmd& value);
std::ostream& operator<<(std::ostream& os, const DetachLightCmd& value);
std::ostream& operator<<(std::ostream& os, const DetachLightsCmd& value);
std::ostream& operator<<(std::ostream& os, const SetTextureCmd& value);
std::ostream& operator<<(std::ostream& os, const SetColorCmd& value);
std::ostream& operator<<(std::ostream& os, const MeshVertexFormat& value);
std::ostream& operator<<(std::ostream& os, const BindMeshBuffersCmd& value);
std::ostream& operator<<(std::ostream& os, const AddLayerCmd& value);
std::ostream& operator<<(std::ostream& os, const RemoveLayerCmd& value);
std::ostream& operator<<(std::ostream& os, const RemoveAllLayersCmd& value);
std::ostream& operator<<(std::ostream& os, const SetLayerStackCmd& value);
std::ostream& operator<<(std::ostream& os, const SetRendererCmd& value);
std::ostream& operator<<(std::ostream& os, const SetRendererParamCmd& value);
std::ostream& operator<<(std::ostream& os, const SetEventMaskCmd& value);
std::ostream& operator<<(std::ostream& os, const SetLabelCmd& value);
std::ostream& operator<<(std::ostream& os, const SetDisableClippingCmd& value);
std::ostream& operator<<(std::ostream& os, const SetImportFocusCmdDEPRECATED& value);
std::ostream& operator<<(std::ostream& os, const SetClipPlanesCmd& value);
std::ostream& operator<<(std::ostream& os, const SetPointLightPositionCmd& value);
std::ostream& operator<<(std::ostream& os, const SetPointLightFalloffCmd& value);
std::ostream& operator<<(std::ostream& os, const SceneAddAmbientLightCmd& value);
std::ostream& operator<<(std::ostream& os, const SceneAddDirectionalLightCmd& value);
std::ostream& operator<<(std::ostream& os, const SceneAddPointLightCmd& value);
std::ostream& operator<<(std::ostream& os, const SetDisplayColorConversionCmdHACK& value);
std::ostream& operator<<(std::ostream& os, const SetDisplayRotationCmdHACK& value);
std::ostream& operator<<(std::ostream& os, const SetEnableDebugViewBoundsCmd& value);
std::ostream& operator<<(std::ostream& os, const SetViewHolderBoundsColorCmd& value);
std::ostream& operator<<(std::ostream& os, const SetDisplayMinimumRgbCmdHACK& value);
std::ostream& operator<<(std::ostream& os, const DisplayInfo& value);
std::ostream& operator<<(std::ostream& os, const MetricsEvent& value);
std::ostream& operator<<(std::ostream& os, const SizeChangeHintEvent& value);
std::ostream& operator<<(std::ostream& os, const ImportUnboundEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewConnectedEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewDisconnectedEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewHolderDisconnectedEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewHolderConnectedEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewAttachedToSceneEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewDetachedFromSceneEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewPropertiesChangedEvent& value);
std::ostream& operator<<(std::ostream& os, const ViewStateChangedEvent& value);
std::ostream& operator<<(std::ostream& os, const ShapeNodeArgs& value);
std::ostream& operator<<(std::ostream& os, const ClipNodeArgs& value);
std::ostream& operator<<(std::ostream& os, const OpacityNodeArgsHACK& value);
std::ostream& operator<<(std::ostream& os, const EntityNodeArgs& value);
std::ostream& operator<<(std::ostream& os, const ImagePipeArgs& value);
std::ostream& operator<<(std::ostream& os, const ImagePipe2Args& value);
std::ostream& operator<<(std::ostream& os, const MemoryArgs& value);
std::ostream& operator<<(std::ostream& os, const ImageArgs& value);
std::ostream& operator<<(std::ostream& os, const ImageArgs2& value);
std::ostream& operator<<(std::ostream& os, const ImageArgs3& value);
std::ostream& operator<<(std::ostream& os, const BufferArgs& value);
std::ostream& operator<<(std::ostream& os, const ViewArgs& value);
std::ostream& operator<<(std::ostream& os, const ViewArgs3& value);
std::ostream& operator<<(std::ostream& os, const ViewHolderArgs& value);
std::ostream& operator<<(std::ostream& os, const CompositorArgs& value);
std::ostream& operator<<(std::ostream& os, const DisplayCompositorArgs& value);
std::ostream& operator<<(std::ostream& os, const ImagePipeCompositorArgs& value);
std::ostream& operator<<(std::ostream& os, const LayerStackArgs& value);
std::ostream& operator<<(std::ostream& os, const LayerArgs& value);
std::ostream& operator<<(std::ostream& os, const SceneArgs& value);
std::ostream& operator<<(std::ostream& os, const CameraArgs& value);
std::ostream& operator<<(std::ostream& os, const StereoCameraArgs& value);
std::ostream& operator<<(std::ostream& os, const RendererArgs& value);
std::ostream& operator<<(std::ostream& os, const AmbientLightArgs& value);
std::ostream& operator<<(std::ostream& os, const DirectionalLightArgs& value);
std::ostream& operator<<(std::ostream& os, const PointLightArgs& value);
std::ostream& operator<<(std::ostream& os, const MaterialArgs& value);
std::ostream& operator<<(std::ostream& os, const VariableArgs& value);
std::ostream& operator<<(std::ostream& os, const RectangleArgs& value);
std::ostream& operator<<(std::ostream& os, const RoundedRectangleArgs& value);
std::ostream& operator<<(std::ostream& os, const CircleArgs& value);
std::ostream& operator<<(std::ostream& os, const MeshArgs& value);
std::ostream& operator<<(std::ostream& os, const ImportToken& value);
std::ostream& operator<<(std::ostream& os, const ExportToken& value);
std::ostream& operator<<(std::ostream& os, const vec2& value);
std::ostream& operator<<(std::ostream& os, const vec3& value);
std::ostream& operator<<(std::ostream& os, const vec4& value);
std::ostream& operator<<(std::ostream& os, const mat4& value);
std::ostream& operator<<(std::ostream& os, const ColorRgba& value);
std::ostream& operator<<(std::ostream& os, const ColorRgb& value);
std::ostream& operator<<(std::ostream& os, const Quaternion& value);
std::ostream& operator<<(std::ostream& os, const Plane3& value);
std::ostream& operator<<(std::ostream& os, const FactoredTransform& value);
std::ostream& operator<<(std::ostream& os, const FloatValue& value);
std::ostream& operator<<(std::ostream& os, const Vector2Value& value);
std::ostream& operator<<(std::ostream& os, const Vector3Value& value);
std::ostream& operator<<(std::ostream& os, const Vector4Value& value);
std::ostream& operator<<(std::ostream& os, const Matrix4Value& value);
std::ostream& operator<<(std::ostream& os, const ColorRgbValue& value);
std::ostream& operator<<(std::ostream& os, const ColorRgbaValue& value);
std::ostream& operator<<(std::ostream& os, const QuaternionValue& value);
std::ostream& operator<<(std::ostream& os, const Metrics& value);
std::ostream& operator<<(std::ostream& os, const BoundingBox& value);
std::ostream& operator<<(std::ostream& os, const ViewProperties& value);
std::ostream& operator<<(std::ostream& os, const ViewState& value);
std::ostream& operator<<(std::ostream& os, const Command& value);
std::ostream& operator<<(std::ostream& os, const Event& value);
std::ostream& operator<<(std::ostream& os, const RendererParam& value);
std::ostream& operator<<(std::ostream& os, const ResourceArgs& value);
std::ostream& operator<<(std::ostream& os, const Value& value);

} // namespace gfx
} // namespace ui
} // namespace fuchsia
