// Copyright 2018 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// WARNING: This file is machine generated by fidlmerge.

#include "lib/fostr/fidl/fuchsia/ui/gfx/formatting.h"

#include "lib/fostr/fidl_types.h"
#include "lib/fostr/fidl/fuchsia/images/formatting.h"
#include "lib/fostr/fidl/fuchsia/mem/formatting.h"
#include "lib/fostr/fidl/fuchsia/scenic/allocation/formatting.h"
#include "lib/fostr/fidl/fuchsia/ui/views/formatting.h"
#include "lib/fostr/fidl/zx/formatting.h"

namespace fuchsia {
namespace ui {
namespace gfx {

template <typename T>
std::ostream& operator<<(std::ostream& os, const std::unique_ptr<T>& value) {
  using fidl::operator<<;
  if (!value) {
    return os << "<null>";
  }

  return os << *value;
}

std::ostream& operator<<(std::ostream& os, const MeshIndexFormat& value) {
  using fidl::operator<<;
  switch (value) {
    case MeshIndexFormat::kUint16:
      return os << "k uint16";
    case MeshIndexFormat::kUint32:
      return os << "k uint32";
    default:
      return os
        << "<invalid enum value: "
        << static_cast<uint32_t>(value)
        << ">" ;
  }
}
std::ostream& operator<<(std::ostream& os, const ShadowTechnique& value) {
  using fidl::operator<<;
  switch (value) {
    case ShadowTechnique::UNSHADOWED:
      return os << "unshadowed";
    case ShadowTechnique::SCREEN_SPACE:
      return os << "screen space";
    case ShadowTechnique::SHADOW_MAP:
      return os << "shadow map";
    case ShadowTechnique::MOMENT_SHADOW_MAP:
      return os << "moment shadow map";
    case ShadowTechnique::STENCIL_SHADOW_VOLUME:
      return os << "stencil shadow volume";
    default:
      return os
        << "<invalid enum value: "
        << static_cast<uint32_t>(value)
        << ">" ;
  }
}
std::ostream& operator<<(std::ostream& os, const RenderFrequency& value) {
  using fidl::operator<<;
  switch (value) {
    case RenderFrequency::WHEN_REQUESTED:
      return os << "when requested";
    case RenderFrequency::CONTINUOUSLY:
      return os << "continuously";
    default:
      return os
        << "<invalid enum value: "
        << static_cast<uint32_t>(value)
        << ">" ;
  }
}
std::ostream& operator<<(std::ostream& os, const ImportSpec& value) {
  using fidl::operator<<;
  switch (value) {
    case ImportSpec::NODE:
      return os << "node";
    default:
      return os
        << "<invalid enum value: "
        << static_cast<uint32_t>(value)
        << ">" ;
  }
}
std::ostream& operator<<(std::ostream& os, const ValueType& value) {
  using fidl::operator<<;
  switch (value) {
    case ValueType::kNone:
      return os << "k none";
    case ValueType::kVector1:
      return os << "k vector1";
    case ValueType::kVector2:
      return os << "k vector2";
    case ValueType::kVector3:
      return os << "k vector3";
    case ValueType::kVector4:
      return os << "k vector4";
    case ValueType::kMatrix4:
      return os << "k matrix4";
    case ValueType::kColorRgb:
      return os << "k color rgb";
    case ValueType::kColorRgba:
      return os << "k color rgba";
    case ValueType::kQuaternion:
      return os << "k quaternion";
    case ValueType::kFactoredTransform:
      return os << "k factored transform";
    default:
      return os
        << "<invalid enum value: "
        << static_cast<uint32_t>(value)
        << ">" ;
  }
}
std::ostream& operator<<(std::ostream& os, const HitTestBehavior& value) {
  using fidl::operator<<;
  switch (value) {
    case HitTestBehavior::kDefault:
      return os << "k default";
    case HitTestBehavior::kSuppress:
      return os << "k suppress";
    default:
      return os
        << "<invalid enum value: "
        << static_cast<uint32_t>(value)
        << ">" ;
  }
}

std::ostream& operator<<(std::ostream& os, const CreateResourceCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "resource: " << value.resource;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ReleaseResourceCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ExportResourceCmdDeprecated& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "token: " << value.token;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImportResourceCmdDeprecated& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "token: " << value.token;
  os << ::fostr::NewLine << "spec: " << value.spec;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetTagCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "tag_value: " << value.tag_value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const DetachCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetTranslationCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "value: " << value.value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetScaleCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "value: " << value.value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetRotationCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "value: " << value.value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetAnchorCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "value: " << value.value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetSizeCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "value: " << value.value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetOpacityCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "opacity: " << value.opacity;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SendSizeChangeHintCmdHACK& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "width_change_factor: " << value.width_change_factor;
  os << ::fostr::NewLine << "height_change_factor: " << value.height_change_factor;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const AddChildCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "child_id: " << value.child_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const AddPartCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "part_id: " << value.part_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const DetachChildrenCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetShapeCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "shape_id: " << value.shape_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetMaterialCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "material_id: " << value.material_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetClipCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "clip_id: " << value.clip_id;
  os << ::fostr::NewLine << "clip_to_self: " << value.clip_to_self;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetHitTestBehaviorCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "hit_test_behavior: " << value.hit_test_behavior;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetSemanticVisibilityCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "visible: " << value.visible;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetViewPropertiesCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_holder_id: " << value.view_holder_id;
  os << ::fostr::NewLine << "properties: " << value.properties;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const TakeSnapshotCmdDEPRECATED& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "callback: " << value.callback;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetCameraCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "renderer_id: " << value.renderer_id;
  os << ::fostr::NewLine << "camera_id: " << value.camera_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetCameraTransformCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "camera_id: " << value.camera_id;
  os << ::fostr::NewLine << "eye_position: " << value.eye_position;
  os << ::fostr::NewLine << "eye_look_at: " << value.eye_look_at;
  os << ::fostr::NewLine << "eye_up: " << value.eye_up;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetCameraProjectionCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "camera_id: " << value.camera_id;
  os << ::fostr::NewLine << "fovy: " << value.fovy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetStereoCameraProjectionCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "camera_id: " << value.camera_id;
  os << ::fostr::NewLine << "left_projection: " << value.left_projection;
  os << ::fostr::NewLine << "right_projection: " << value.right_projection;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetCameraClipSpaceTransformCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "camera_id: " << value.camera_id;
  os << ::fostr::NewLine << "translation: " << value.translation;
  os << ::fostr::NewLine << "scale: " << value.scale;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetCameraPoseBufferCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "camera_id: " << value.camera_id;
  os << ::fostr::NewLine << "buffer_id: " << value.buffer_id;
  os << ::fostr::NewLine << "num_entries: " << value.num_entries;
  os << ::fostr::NewLine << "base_time: " << value.base_time;
  os << ::fostr::NewLine << "time_interval: " << value.time_interval;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetLightColorCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  os << ::fostr::NewLine << "color: " << value.color;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetLightDirectionCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  os << ::fostr::NewLine << "direction: " << value.direction;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const AddLightCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scene_id: " << value.scene_id;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const DetachLightCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const DetachLightsCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scene_id: " << value.scene_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetTextureCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "material_id: " << value.material_id;
  os << ::fostr::NewLine << "texture_id: " << value.texture_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetColorCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "material_id: " << value.material_id;
  os << ::fostr::NewLine << "color: " << value.color;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const MeshVertexFormat& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "position_type: " << value.position_type;
  os << ::fostr::NewLine << "normal_type: " << value.normal_type;
  os << ::fostr::NewLine << "tex_coord_type: " << value.tex_coord_type;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const BindMeshBuffersCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "mesh_id: " << value.mesh_id;
  os << ::fostr::NewLine << "index_buffer_id: " << value.index_buffer_id;
  os << ::fostr::NewLine << "index_format: " << value.index_format;
  os << ::fostr::NewLine << "index_offset: " << value.index_offset;
  os << ::fostr::NewLine << "index_count: " << value.index_count;
  os << ::fostr::NewLine << "vertex_buffer_id: " << value.vertex_buffer_id;
  os << ::fostr::NewLine << "vertex_format: " << value.vertex_format;
  os << ::fostr::NewLine << "vertex_offset: " << value.vertex_offset;
  os << ::fostr::NewLine << "vertex_count: " << value.vertex_count;
  os << ::fostr::NewLine << "bounding_box: " << value.bounding_box;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const AddLayerCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "layer_stack_id: " << value.layer_stack_id;
  os << ::fostr::NewLine << "layer_id: " << value.layer_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const RemoveLayerCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "layer_stack_id: " << value.layer_stack_id;
  os << ::fostr::NewLine << "layer_id: " << value.layer_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const RemoveAllLayersCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "layer_stack_id: " << value.layer_stack_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetLayerStackCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "compositor_id: " << value.compositor_id;
  os << ::fostr::NewLine << "layer_stack_id: " << value.layer_stack_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetRendererCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "layer_id: " << value.layer_id;
  os << ::fostr::NewLine << "renderer_id: " << value.renderer_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetRendererParamCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "renderer_id: " << value.renderer_id;
  os << ::fostr::NewLine << "param: " << value.param;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetEventMaskCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "event_mask: " << value.event_mask;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetLabelCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "id: " << value.id;
  os << ::fostr::NewLine << "label: " << value.label;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetDisableClippingCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "renderer_id: " << value.renderer_id;
  os << ::fostr::NewLine << "disable_clipping: " << value.disable_clipping;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetImportFocusCmdDEPRECATED& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetClipPlanesCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "clip_planes: " << ::fostr::PrintVector(value.clip_planes);
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetPointLightPositionCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  os << ::fostr::NewLine << "position: " << value.position;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetPointLightFalloffCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  os << ::fostr::NewLine << "falloff: " << value.falloff;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SceneAddAmbientLightCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scene_id: " << value.scene_id;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SceneAddDirectionalLightCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scene_id: " << value.scene_id;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SceneAddPointLightCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scene_id: " << value.scene_id;
  os << ::fostr::NewLine << "light_id: " << value.light_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetDisplayColorConversionCmdHACK& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "compositor_id: " << value.compositor_id;
  os << ::fostr::NewLine << "preoffsets: " << value.preoffsets;
  os << ::fostr::NewLine << "matrix: " << value.matrix;
  os << ::fostr::NewLine << "postoffsets: " << value.postoffsets;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetDisplayRotationCmdHACK& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "compositor_id: " << value.compositor_id;
  os << ::fostr::NewLine << "rotation_degrees: " << value.rotation_degrees;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetEnableDebugViewBoundsCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_id: " << value.view_id;
  os << ::fostr::NewLine << "enable: " << value.enable;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetViewHolderBoundsColorCmd& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_holder_id: " << value.view_holder_id;
  os << ::fostr::NewLine << "color: " << value.color;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SetDisplayMinimumRgbCmdHACK& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "min_value: " << static_cast<uint32_t>(value.min_value);
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const DisplayInfo& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "width_in_px: " << value.width_in_px;
  os << ::fostr::NewLine << "height_in_px: " << value.height_in_px;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const MetricsEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "metrics: " << value.metrics;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SizeChangeHintEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "node_id: " << value.node_id;
  os << ::fostr::NewLine << "width_change_factor: " << value.width_change_factor;
  os << ::fostr::NewLine << "height_change_factor: " << value.height_change_factor;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImportUnboundEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "resource_id: " << value.resource_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewConnectedEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_holder_id: " << value.view_holder_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewDisconnectedEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_holder_id: " << value.view_holder_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewHolderDisconnectedEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_id: " << value.view_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewHolderConnectedEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_id: " << value.view_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewAttachedToSceneEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_id: " << value.view_id;
  os << ::fostr::NewLine << "properties: " << value.properties;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewDetachedFromSceneEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_id: " << value.view_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewPropertiesChangedEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_id: " << value.view_id;
  os << ::fostr::NewLine << "properties: " << value.properties;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewStateChangedEvent& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "view_holder_id: " << value.view_holder_id;
  os << ::fostr::NewLine << "state: " << value.state;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Hit& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "tag_value: " << value.tag_value;
  os << ::fostr::NewLine << "ray_origin: " << value.ray_origin;
  os << ::fostr::NewLine << "ray_direction: " << value.ray_direction;
  os << ::fostr::NewLine << "inverse_transform: " << value.inverse_transform;
  os << ::fostr::NewLine << "distance: " << value.distance;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ShapeNodeArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "unused: " << value.unused;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ClipNodeArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "unused: " << value.unused;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const OpacityNodeArgsHACK& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "unused: " << value.unused;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const EntityNodeArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "unused: " << value.unused;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImagePipeArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "image_pipe_request: " << value.image_pipe_request;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImagePipe2Args& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "image_pipe_request: " << value.image_pipe_request;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const MemoryArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "vmo: " << value.vmo;
  os << ::fostr::NewLine << "allocation_size: " << value.allocation_size;
  os << ::fostr::NewLine << "memory_type: " << value.memory_type;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImageArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "info: " << value.info;
  os << ::fostr::NewLine << "memory_id: " << value.memory_id;
  os << ::fostr::NewLine << "memory_offset: " << value.memory_offset;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImageArgs2& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "width: " << value.width;
  os << ::fostr::NewLine << "height: " << value.height;
  os << ::fostr::NewLine << "buffer_collection_id: " << value.buffer_collection_id;
  os << ::fostr::NewLine << "buffer_collection_index: " << value.buffer_collection_index;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImageArgs3& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "width: " << value.width;
  os << ::fostr::NewLine << "height: " << value.height;
  os << ::fostr::NewLine << "import_token: " << value.import_token;
  os << ::fostr::NewLine << "buffer_collection_index: " << value.buffer_collection_index;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const BufferArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "memory_id: " << value.memory_id;
  os << ::fostr::NewLine << "memory_offset: " << value.memory_offset;
  os << ::fostr::NewLine << "num_bytes: " << value.num_bytes;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "token: " << value.token;
  os << ::fostr::NewLine << "debug_name: " << value.debug_name;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewArgs3& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "token: " << value.token;
  os << ::fostr::NewLine << "control_ref: " << value.control_ref;
  os << ::fostr::NewLine << "view_ref: " << value.view_ref;
  os << ::fostr::NewLine << "debug_name: " << value.debug_name;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewHolderArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "token: " << value.token;
  os << ::fostr::NewLine << "debug_name: " << value.debug_name;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const CompositorArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const DisplayCompositorArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImagePipeCompositorArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "target: " << value.target;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const LayerStackArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const LayerArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const SceneArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const CameraArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scene_id: " << value.scene_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const StereoCameraArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scene_id: " << value.scene_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const RendererArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const AmbientLightArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const DirectionalLightArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const PointLightArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const MaterialArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dummy: " << value.dummy;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const VariableArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "type: " << value.type;
  os << ::fostr::NewLine << "initial_value: " << value.initial_value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const RectangleArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "width: " << value.width;
  os << ::fostr::NewLine << "height: " << value.height;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const RoundedRectangleArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "width: " << value.width;
  os << ::fostr::NewLine << "height: " << value.height;
  os << ::fostr::NewLine << "top_left_radius: " << value.top_left_radius;
  os << ::fostr::NewLine << "top_right_radius: " << value.top_right_radius;
  os << ::fostr::NewLine << "bottom_right_radius: " << value.bottom_right_radius;
  os << ::fostr::NewLine << "bottom_left_radius: " << value.bottom_left_radius;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const CircleArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "radius: " << value.radius;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const MeshArgs& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ImportToken& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ExportToken& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const vec2& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "x: " << value.x;
  os << ::fostr::NewLine << "y: " << value.y;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const vec3& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "x: " << value.x;
  os << ::fostr::NewLine << "y: " << value.y;
  os << ::fostr::NewLine << "z: " << value.z;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const vec4& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "x: " << value.x;
  os << ::fostr::NewLine << "y: " << value.y;
  os << ::fostr::NewLine << "z: " << value.z;
  os << ::fostr::NewLine << "w: " << value.w;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const mat4& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "matrix: " << value.matrix;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ColorRgba& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "red: " << static_cast<uint32_t>(value.red);
  os << ::fostr::NewLine << "green: " << static_cast<uint32_t>(value.green);
  os << ::fostr::NewLine << "blue: " << static_cast<uint32_t>(value.blue);
  os << ::fostr::NewLine << "alpha: " << static_cast<uint32_t>(value.alpha);
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ColorRgb& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "red: " << value.red;
  os << ::fostr::NewLine << "green: " << value.green;
  os << ::fostr::NewLine << "blue: " << value.blue;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Quaternion& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "x: " << value.x;
  os << ::fostr::NewLine << "y: " << value.y;
  os << ::fostr::NewLine << "z: " << value.z;
  os << ::fostr::NewLine << "w: " << value.w;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Plane3& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "dir: " << value.dir;
  os << ::fostr::NewLine << "dist: " << value.dist;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const FactoredTransform& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "translation: " << value.translation;
  os << ::fostr::NewLine << "scale: " << value.scale;
  os << ::fostr::NewLine << "anchor: " << value.anchor;
  os << ::fostr::NewLine << "rotation: " << value.rotation;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const FloatValue& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Vector2Value& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Vector3Value& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Vector4Value& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Matrix4Value& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ColorRgbValue& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ColorRgbaValue& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const QuaternionValue& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "value: " << value.value;
  os << ::fostr::NewLine << "variable_id: " << value.variable_id;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Metrics& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "scale_x: " << value.scale_x;
  os << ::fostr::NewLine << "scale_y: " << value.scale_y;
  os << ::fostr::NewLine << "scale_z: " << value.scale_z;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const BoundingBox& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "min: " << value.min;
  os << ::fostr::NewLine << "max: " << value.max;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewProperties& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "bounding_box: " << value.bounding_box;
  os << ::fostr::NewLine << "inset_from_min: " << value.inset_from_min;
  os << ::fostr::NewLine << "inset_from_max: " << value.inset_from_max;
  os << ::fostr::NewLine << "focus_change: " << value.focus_change;
  os << ::fostr::NewLine << "downward_input: " << value.downward_input;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const ViewState& value) {
  using fidl::operator<<;
  os << ::fostr::Indent;
  os << ::fostr::NewLine << "is_rendering: " << value.is_rendering;
  return os << ::fostr::Outdent;
}

std::ostream& operator<<(std::ostream& os, const Command& value) {
  using fidl::operator<<;
  switch (value.Ordinal()) {
    case Command::Tag::kCreateResource:
      return os << "create_resource " << value.create_resource();
    case Command::Tag::kReleaseResource:
      return os << "release_resource " << value.release_resource();
    case Command::Tag::kExportResource:
      return os << "export_resource " << value.export_resource();
    case Command::Tag::kImportResource:
      return os << "import_resource " << value.import_resource();
    case Command::Tag::kSetTag:
      return os << "set_tag " << value.set_tag();
    case Command::Tag::kDetach:
      return os << "detach " << value.detach();
    case Command::Tag::kSetTranslation:
      return os << "set_translation " << value.set_translation();
    case Command::Tag::kSetScale:
      return os << "set_scale " << value.set_scale();
    case Command::Tag::kSetRotation:
      return os << "set_rotation " << value.set_rotation();
    case Command::Tag::kSetAnchor:
      return os << "set_anchor " << value.set_anchor();
    case Command::Tag::kSetSize:
      return os << "set_size " << value.set_size();
    case Command::Tag::kSetOpacity:
      return os << "set_opacity " << value.set_opacity();
    case Command::Tag::kSendSizeChangeHintHack:
      return os << "send_size_change_hint_hack " << value.send_size_change_hint_hack();
    case Command::Tag::kAddChild:
      return os << "add_child " << value.add_child();
    case Command::Tag::kAddPart:
      return os << "add_part " << value.add_part();
    case Command::Tag::kDetachChildren:
      return os << "detach_children " << value.detach_children();
    case Command::Tag::kSetShape:
      return os << "set_shape " << value.set_shape();
    case Command::Tag::kSetMaterial:
      return os << "set_material " << value.set_material();
    case Command::Tag::kSetClip:
      return os << "set_clip " << value.set_clip();
    case Command::Tag::kSetHitTestBehavior:
      return os << "set_hit_test_behavior " << value.set_hit_test_behavior();
    case Command::Tag::kSetViewProperties:
      return os << "set_view_properties " << value.set_view_properties();
    case Command::Tag::kTakeSnapshotCmd:
      return os << "take_snapshot_cmd " << value.take_snapshot_cmd();
    case Command::Tag::kSetCamera:
      return os << "set_camera " << value.set_camera();
    case Command::Tag::kSetCameraTransform:
      return os << "set_camera_transform " << value.set_camera_transform();
    case Command::Tag::kSetCameraProjection:
      return os << "set_camera_projection " << value.set_camera_projection();
    case Command::Tag::kSetStereoCameraProjection:
      return os << "set_stereo_camera_projection " << value.set_stereo_camera_projection();
    case Command::Tag::kSetCameraPoseBuffer:
      return os << "set_camera_pose_buffer " << value.set_camera_pose_buffer();
    case Command::Tag::kSetLightColor:
      return os << "set_light_color " << value.set_light_color();
    case Command::Tag::kSetLightDirection:
      return os << "set_light_direction " << value.set_light_direction();
    case Command::Tag::kAddLight:
      return os << "add_light " << value.add_light();
    case Command::Tag::kDetachLight:
      return os << "detach_light " << value.detach_light();
    case Command::Tag::kDetachLights:
      return os << "detach_lights " << value.detach_lights();
    case Command::Tag::kSetTexture:
      return os << "set_texture " << value.set_texture();
    case Command::Tag::kSetColor:
      return os << "set_color " << value.set_color();
    case Command::Tag::kBindMeshBuffers:
      return os << "bind_mesh_buffers " << value.bind_mesh_buffers();
    case Command::Tag::kAddLayer:
      return os << "add_layer " << value.add_layer();
    case Command::Tag::kRemoveLayer:
      return os << "remove_layer " << value.remove_layer();
    case Command::Tag::kRemoveAllLayers:
      return os << "remove_all_layers " << value.remove_all_layers();
    case Command::Tag::kSetLayerStack:
      return os << "set_layer_stack " << value.set_layer_stack();
    case Command::Tag::kSetRenderer:
      return os << "set_renderer " << value.set_renderer();
    case Command::Tag::kSetRendererParam:
      return os << "set_renderer_param " << value.set_renderer_param();
    case Command::Tag::kSetEventMask:
      return os << "set_event_mask " << value.set_event_mask();
    case Command::Tag::kSetLabel:
      return os << "set_label " << value.set_label();
    case Command::Tag::kSetDisableClipping:
      return os << "set_disable_clipping " << value.set_disable_clipping();
    case Command::Tag::kSetImportFocus:
      return os << "set_import_focus " << value.set_import_focus();
    case Command::Tag::kSetClipPlanes:
      return os << "set_clip_planes " << value.set_clip_planes();
    case Command::Tag::kSetPointLightPosition:
      return os << "set_point_light_position " << value.set_point_light_position();
    case Command::Tag::kSetPointLightFalloff:
      return os << "set_point_light_falloff " << value.set_point_light_falloff();
    case Command::Tag::kScene_AddAmbientLight:
      return os << "scene__add_ambient_light " << value.scene__add_ambient_light();
    case Command::Tag::kScene_AddDirectionalLight:
      return os << "scene__add_directional_light " << value.scene__add_directional_light();
    case Command::Tag::kScene_AddPointLight:
      return os << "scene__add_point_light " << value.scene__add_point_light();
    case Command::Tag::kSetDisplayColorConversion:
      return os << "set_display_color_conversion " << value.set_display_color_conversion();
    case Command::Tag::kSetDisplayRotation:
      return os << "set_display_rotation " << value.set_display_rotation();
    case Command::Tag::kSetEnableViewDebugBounds:
      return os << "set_enable_view_debug_bounds " << value.set_enable_view_debug_bounds();
    case Command::Tag::kSetViewHolderBoundsColor:
      return os << "set_view_holder_bounds_color " << value.set_view_holder_bounds_color();
    case Command::Tag::kSetCameraClipSpaceTransform:
      return os << "set_camera_clip_space_transform " << value.set_camera_clip_space_transform();
    case Command::Tag::kSetDisplayMinimumRgb:
      return os << "set_display_minimum_rgb " << value.set_display_minimum_rgb();
    case Command::Tag::kSetSemanticVisibility:
      return os << "set_semantic_visibility " << value.set_semantic_visibility();
    case static_cast<fidl_xunion_tag_t>(Command::Tag::Invalid):
      return os << "<empty union>";
  }

  return os;
}

std::ostream& operator<<(std::ostream& os, const Event& value) {
  using fidl::operator<<;
  switch (value.Ordinal()) {
    case Event::Tag::kMetrics:
      return os << "metrics " << value.metrics();
    case Event::Tag::kSizeChangeHint:
      return os << "size_change_hint " << value.size_change_hint();
    case Event::Tag::kImportUnbound:
      return os << "import_unbound " << value.import_unbound();
    case Event::Tag::kViewConnected:
      return os << "view_connected " << value.view_connected();
    case Event::Tag::kViewDisconnected:
      return os << "view_disconnected " << value.view_disconnected();
    case Event::Tag::kViewHolderDisconnected:
      return os << "view_holder_disconnected " << value.view_holder_disconnected();
    case Event::Tag::kViewAttachedToScene:
      return os << "view_attached_to_scene " << value.view_attached_to_scene();
    case Event::Tag::kViewDetachedFromScene:
      return os << "view_detached_from_scene " << value.view_detached_from_scene();
    case Event::Tag::kViewPropertiesChanged:
      return os << "view_properties_changed " << value.view_properties_changed();
    case Event::Tag::kViewStateChanged:
      return os << "view_state_changed " << value.view_state_changed();
    case Event::Tag::kViewHolderConnected:
      return os << "view_holder_connected " << value.view_holder_connected();
    case static_cast<fidl_xunion_tag_t>(Event::Tag::Invalid):
      return os << "<empty union>";
  }

  return os;
}

std::ostream& operator<<(std::ostream& os, const RendererParam& value) {
  using fidl::operator<<;
  switch (value.Ordinal()) {
    case RendererParam::Tag::kShadowTechnique:
      return os << "shadow_technique " << value.shadow_technique();
    case RendererParam::Tag::kReserved:
      return os << "reserved " << value.reserved();
    case RendererParam::Tag::kEnableDebugging:
      return os << "enable_debugging " << value.enable_debugging();
    case static_cast<fidl_xunion_tag_t>(RendererParam::Tag::Invalid):
      return os << "<empty union>";
  }

  return os;
}

std::ostream& operator<<(std::ostream& os, const ResourceArgs& value) {
  using fidl::operator<<;
  switch (value.Ordinal()) {
    case ResourceArgs::Tag::kMemory:
      return os << "memory " << value.memory();
    case ResourceArgs::Tag::kImage:
      return os << "image " << value.image();
    case ResourceArgs::Tag::kImagePipe:
      return os << "image_pipe " << value.image_pipe();
    case ResourceArgs::Tag::kBuffer:
      return os << "buffer " << value.buffer();
    case ResourceArgs::Tag::kView:
      return os << "view " << value.view();
    case ResourceArgs::Tag::kViewHolder:
      return os << "view_holder " << value.view_holder();
    case ResourceArgs::Tag::kRectangle:
      return os << "rectangle " << value.rectangle();
    case ResourceArgs::Tag::kRoundedRectangle:
      return os << "rounded_rectangle " << value.rounded_rectangle();
    case ResourceArgs::Tag::kCircle:
      return os << "circle " << value.circle();
    case ResourceArgs::Tag::kMesh:
      return os << "mesh " << value.mesh();
    case ResourceArgs::Tag::kShapeNode:
      return os << "shape_node " << value.shape_node();
    case ResourceArgs::Tag::kClipNode:
      return os << "clip_node " << value.clip_node();
    case ResourceArgs::Tag::kEntityNode:
      return os << "entity_node " << value.entity_node();
    case ResourceArgs::Tag::kOpacityNode:
      return os << "opacity_node " << value.opacity_node();
    case ResourceArgs::Tag::kMaterial:
      return os << "material " << value.material();
    case ResourceArgs::Tag::kCompositor:
      return os << "compositor " << value.compositor();
    case ResourceArgs::Tag::kDisplayCompositor:
      return os << "display_compositor " << value.display_compositor();
    case ResourceArgs::Tag::kImagePipeCompositor:
      return os << "image_pipe_compositor " << value.image_pipe_compositor();
    case ResourceArgs::Tag::kLayerStack:
      return os << "layer_stack " << value.layer_stack();
    case ResourceArgs::Tag::kLayer:
      return os << "layer " << value.layer();
    case ResourceArgs::Tag::kScene:
      return os << "scene " << value.scene();
    case ResourceArgs::Tag::kCamera:
      return os << "camera " << value.camera();
    case ResourceArgs::Tag::kStereoCamera:
      return os << "stereo_camera " << value.stereo_camera();
    case ResourceArgs::Tag::kRenderer:
      return os << "renderer " << value.renderer();
    case ResourceArgs::Tag::kAmbientLight:
      return os << "ambient_light " << value.ambient_light();
    case ResourceArgs::Tag::kDirectionalLight:
      return os << "directional_light " << value.directional_light();
    case ResourceArgs::Tag::kVariable:
      return os << "variable " << value.variable();
    case ResourceArgs::Tag::kPointLight:
      return os << "point_light " << value.point_light();
    case ResourceArgs::Tag::kView3:
      return os << "view3 " << value.view3();
    case ResourceArgs::Tag::kImagePipe2:
      return os << "image_pipe2 " << value.image_pipe2();
    case ResourceArgs::Tag::kImage2:
      return os << "image2 " << value.image2();
    case ResourceArgs::Tag::kImage3:
      return os << "image3 " << value.image3();
    case static_cast<fidl_xunion_tag_t>(ResourceArgs::Tag::Invalid):
      return os << "<empty union>";
  }

  return os;
}

std::ostream& operator<<(std::ostream& os, const Value& value) {
  using fidl::operator<<;
  switch (value.Ordinal()) {
    case Value::Tag::kVector1:
      return os << "vector1 " << value.vector1();
    case Value::Tag::kVector2:
      return os << "vector2 " << value.vector2();
    case Value::Tag::kVector3:
      return os << "vector3 " << value.vector3();
    case Value::Tag::kVector4:
      return os << "vector4 " << value.vector4();
    case Value::Tag::kMatrix4x4:
      return os << "matrix4x4 " << value.matrix4x4();
    case Value::Tag::kColorRgba:
      return os << "color_rgba " << value.color_rgba();
    case Value::Tag::kColorRgb:
      return os << "color_rgb " << value.color_rgb();
    case Value::Tag::kDegrees:
      return os << "degrees " << value.degrees();
    case Value::Tag::kQuaternion:
      return os << "quaternion " << value.quaternion();
    case Value::Tag::kTransform:
      return os << "transform " << value.transform();
    case Value::Tag::kVariableId:
      return os << "variable_id " << value.variable_id();
    case static_cast<fidl_xunion_tag_t>(Value::Tag::Invalid):
      return os << "<empty union>";
  }

  return os;
}

} // namespace gfx
} // namespace ui
} // namespace fuchsia
