platform :ios, '12.0'

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

flutter_application_path = 'FlutterModule'
framework_dir = File.join(flutter_application_path, '.ios', 'Flutter')

engine_dir = File.join(framework_dir, 'engine')

target 'OuterApp' do
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end

target 'OuterAppTests' do
  pod 'Flutter', :path => engine_dir
  inherit! :search_paths
  pod 'EarlGrey'
end
